version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  target:
    image: eexit/mirror-http-server
    ports:
      - "8081:80"
  web:
    image: chomnoue/irembo-api-rate-limiter
    environment:
      - SPRING_REDIS_HOST=redis
      - RATE_LIMITED_URI=http://target
      - "RATE_LIMITED_PATH=/limited"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - target
